apiVersion: v1
kind: Service
metadata:
  name: p7-api
spec:
  type: NodePort
  selector:
    app: p7-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: p7-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p7-api
  template:
    metadata:
      labels:
        app: p7-api
    spec:
      containers:
        - name: p7-api
          image: dicesare/p7_api:latest
          ports:
            - containerPort: 80