apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: p7-api
        image: dicesare/p7_api:latest
        command: ["pytest", "test/"]
      restartPolicy: Never
  backoffLimit: 4